services:
  mysql:
    container_name: db-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser-password
    ports:
      - 3307:3306
    volumes:
      - my-db-volume:/var/lib/mysql

volumes:
  my-db-volume: